//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDungeon.Game.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreSet
    {
        public int ScoreID { get; set; }
        public string Level { get; set; }
        public string World { get; set; }
        public string Total { get; set; }
        public int Player_PlayerID { get; set; }
    
        public virtual PlayerSet PlayerSet { get; set; }
    }
}
